-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsQ/eKo7WZHp8Ixjn
h/6SyimXznIicTM3ZQDIZnOoHJugCgYIKoZIzj0DAQehRANCAAQHIxUXkaFLJ4pD
eB/rSZyuhWeW49iM43vybTkj45pAS2qsMBn4ev7aYM9sglLYYBRduh8VJqMaKaUJ
lwa5iDv0
-----END PRIVATE KEY-----